# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# PARALLEL PROGRAMING
# =============================================================================

  parallel-programing:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - parallel-programing

# =============================================================================
# NETWORK
# =============================================================================

networks:
  parallel-programing:
